all: fundamental.cpp
	g++ -g -o fundamental -lcv -lcvaux -lhighgui -I /usr/include/opencv/ fundamental.cpp
	g++ -g -o calibartion -lcv -lcvaux -lhighgui -I /usr/include/opencv/ calibration.cpp

clean:
	rm -rf fundamental.o fundamental calibaration calibaration.o
